version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: p2p
      POSTGRES_USER: p2p
      POSTGRES_PASSWORD: p2p
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # web:
  #   build: .
  #   command: bash -c "python manage.py migrate --noinput && gunicorn procure_to_pay.wsgi:application -b 0.0.0.0:8000"
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgres://p2p:p2p@db:5432/p2p
  #     - REDIS_URL=redis://redis:6379/0
  #     - DJANGO_SETTINGS_MODULE=procure_to_pay.settings
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./:/app

volumes:
  postgres_data: